export const lang = {
  select_variant: " Select a variant",
  select_size: "Select Size",
  select_color: "Select Color",
  search_all_products: "Search all products",
  search_customer: "Search customers",
  no_items_found: "No items found",
  home: "Home",
  orders: "Orders",
  products: "Products",
  categories: "Categories",
  customers: "Customers",
  reports: "Reports",
  quantity: "Quantity",
  discount: "Discount",
  percent: "%",
  amount: "amount",
  currency: "$",
  subtotal: "Subtotal",
  total_tax: "Total tax",
  pay: "Pay",
  apply_discount: "Apply discount to cart",
  select_payment: " Select payment",
  total: "Total",
  cash: "Cash",
  cheque: "Cheque",
  credit_card: "Credit Card",
  order_completed: "Order completed!",
  order_ref: "Order reference",
  customer: "Customer",
  add_customer: "Add a customer",
  discount_msg: "Discount cannot be less than or equal to zero",
  id: "ID",
  reference: "Reference",
  customer: "Customer",
  status: "Status",
  date: "Date",
  order: "Order",
  created_date: "Created date",
  total_products: "Total products",
  delivered: "Delivered",
  permission_dialog_title: "Permission to use camera",
  permission_dialog_messeage:
    "We need your permission to use your camera phone",
  barcode_not_exist: "This barcode does not exist!",
  name: "Name",
  barcode: "Barcode",
  ok: "OK",
  cancel: "Cancel",
  search_item_id: "ID: ",
  search_item_ref: " - Ref: ",
  search_item_stock: " - Stock: ",
  max_char: "250 char. max",
  img_type: ".png .jpg .gif",
  choose_an_img: "Choose an image",
  width: "Width",
  height: "Height",
  weight: "Weight",
  change_this: "Change this",
  stock: "Stock",
  out_of_range_percent: "Discount amount can't be greater than 100%",
  out_of_range_amount:
    "Discount amount can't be greater than price of one product",
  product_is_out_of_stock: "Product is out of stock",
  this_combination_does_not_exist_for_this_product:
    "This combination does not exist for this product",
  required: "*",
  load_more: "Load more",
  please_upload_another_img: "Please upload another image",
  we_need_permission_to_use_this_function:
    "We need permission to use this function"
};

export const api = "http://v2.rockpos.com/module/hspointofsalepro/api";

export const configuration = {
  formatPay: "^[0-9]*(\\.?[0-9]{0,2})$",
  numOfColumns: 5,
  idCategories: [5, 4, 3, 2, 1],
  precision: 2,
  maxLength: 20,
  threeDot: "...",
  percentage: "percentage",
  amount: "amount",
  attributeKeys: {
    sizes: "sizes",
    colors: "colors"
  },
  params: {
    stopSearching: {
      isSearching: null,
      searchResults: [],
      isEmptyResults: false
    },
    backAfterStopSearch: {
      isSearching: false,
      searchResults: [],
      isEmptyResults: false
    }
  },
  productKey: {
    name: "name",
    id_product: "id_product",
    reference: "reference"
  },
  idSizeAttributeGroup: 1,
  search_item_text_format: "ID: %s - Ref: %s - Stock: %s",
  format: {
    price: "$%s",
    discount: "%s (%s)",
    orderRef: "%s: %s",
    name: "%s %s",
    stock: "(%s: %s)",
    minus_price: "-$%s",
    date: "mm/dd/yyyy",
    original_price: "%s x 1 = $%s"
  },
  minCharacterToSearch: 3,
  searchTimeout: 500,
  finderWidth: 450,
  finderHeight: 400,
  finderBorderWidth: 4,
  warningTime: 1000,
  blinkTime: 1000,
  maxLengthPercent: 6,
  maxLengthAmount: 6,
  defaultPrice: "0.00",
  defaultQty: "1",
  emptyPrice: "",
  emptyQty: "",
  regexPrice: `^[0-9]+\\.{0,1}[0-9]{0,2}$`,
  upOperator: "up",
  downOperator: "down",
  text_fields: "text_fields",
  image_fields: "image_fields",
  file: "file",
  text: "text",
  emptyString: "",
  maxPercentageValue: 100,
  defaultReductionType: 0,
  defaultReductionValue: 0,
  search: "search",
  noQuantity: 0,
  searchProduct: "product",
  searchCustomer: "customer"
};
